/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution: string;
  degree: string;
  period?: string;
  status?: string;
  description?: string;
  skills?: Array<string>;
  orderRank?: string;
};

export type SkillCategory = {
  _id: string;
  _type: "skillCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  icon:
    | "Code"
    | "Brain"
    | "Database"
    | "BarChart3"
    | "Wrench"
    | "Cloud"
    | "Cpu"
    | "Layers"
    | "Plug";
  description?: string;
  items?: Array<string>;
  orderRank?: string;
};

export type ProjectCategory = {
  _id: string;
  _type: "projectCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  orderRank?: string;
};

export type ProjectCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectCategory";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  longDescription?: string;
  categories?: Array<
    {
      _key: string;
    } & ProjectCategoryReference
  >;
  tags?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  githubUrl?: string;
  demoUrl?: string;
  featured?: boolean;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role: string;
  company: string;
  companyUrl?: string;
  period: string;
  location?: string;
  summary?: string;
  highlights?: Array<string>;
  skills?: Array<string>;
  orderRank?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  url: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  keywords?: Array<string>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  tagline: string;
  heroDescription: string;
  aboutDescription?: string;
  email: string;
  location?: string;
  availability?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  certifications?: Array<string>;
  githubUrl: string;
  linkedinUrl: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Education
  | SkillCategory
  | ProjectCategory
  | ProjectCategoryReference
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Experience
  | SiteSettings
  | SanityFileAssetReference
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../lib/sanity/queries.ts
// Variable: PORTFOLIO_QUERY
// Query: {  "profile": *[_type == "profile" && _id == "profile"][0]{    name, role, tagline, heroDescription, aboutDescription, email, location,    availability, photo, "resumeUrl": resume.asset->url, certifications,    githubUrl, linkedinUrl  },  "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{    title, description, url, ogImage, keywords  },  "experience": *[_type == "experience"] | order(orderRank) {    _id, role, company, companyUrl, period, location, summary, highlights, skills  },  "categories": *[_type == "projectCategory"] | order(orderRank) { _id, title },  "projects": *[_type == "project"] | order(orderRank) {    _id, title, description, longDescription,    "categories": categories[]->title,    tags, image, githubUrl, demoUrl, featured  },  "skills": *[_type == "skillCategory"] | order(orderRank) {    _id, name, icon, description, items  },  "education": *[_type == "education"] | order(orderRank) {    _id, institution, degree, period, status, description, skills  }}
export type PORTFOLIO_QUERY_RESULT = {
  profile: {
    name: string;
    role: string;
    tagline: string;
    heroDescription: string;
    aboutDescription: string | null;
    email: string;
    location: string | null;
    availability: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    resumeUrl: string | null;
    certifications: Array<string> | null;
    githubUrl: string;
    linkedinUrl: string;
  } | null;
  settings: {
    title: string;
    description: string;
    url: string;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    keywords: Array<string> | null;
  } | null;
  experience: Array<{
    _id: string;
    role: string;
    company: string;
    companyUrl: string | null;
    period: string;
    location: string | null;
    summary: string | null;
    highlights: Array<string> | null;
    skills: Array<string> | null;
  }>;
  categories: Array<{
    _id: string;
    title: string;
  }>;
  projects: Array<{
    _id: string;
    title: string;
    description: string;
    longDescription: string | null;
    categories: Array<string> | null;
    tags: Array<string> | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    githubUrl: string | null;
    demoUrl: string | null;
    featured: boolean | null;
  }>;
  skills: Array<{
    _id: string;
    name: string;
    icon:
      | "BarChart3"
      | "Brain"
      | "Cloud"
      | "Code"
      | "Cpu"
      | "Database"
      | "Layers"
      | "Plug"
      | "Wrench";
    description: string | null;
    items: Array<string> | null;
  }>;
  education: Array<{
    _id: string;
    institution: string;
    degree: string;
    period: string | null;
    status: string | null;
    description: string | null;
    skills: Array<string> | null;
  }>;
};
